#############################
###   shared settings     ###
#############################
x-shared-settings: &shared-settings
  build: 
    context: .  
    dockerfile: Dockerfile
  image: pomelo925/ttennis-humble:nav2
  stdin_open: true
  tty: true
  network_mode: host
  privileged: true
  volumes:
    - /dev/bus/usb:/dev/bus/usb
    - /tmp/.X11-unix:/tmp/.X11-unix
    - $HOME/.Xauthority:/root/.Xauthority
    - /dev/shm:/dev/shm

    - ../nav2-ws/build:/home/nav2-ws/build
    - ../nav2-ws/install:/home/nav2-ws/install
    - ../nav2-ws/src:/home/nav2-ws/src
  environment:
    - DISPLAY=${DISPLAY}
    - COMMAND=${COMMAND}
  devices:
    - /dev/bus/usb:/dev/bus/usb
    

#############################
###   Container Startup   ###
#############################
services:
  navigation-deployment:
    <<: *shared-settings
    container_name: navigation-deployment
    command: "/bin/bash -c \"${COMMAND}\""