#############################
###   shared settings     ###
#############################
x-shared-settings: &shared-settings
  image: pomelo925/ttennis-humble:nav2
  tty: true
  network_mode: host
  privileged: true
  volumes:
    - /dev/bus/usb:/dev/bus/usb
    - /tmp/.X11-unix:/tmp/.X11-unix
    - $HOME/.Xauthority:/root/.Xauthority
    - ../nav2-ws:/root/nav2-ws
  environment:
    - DISPLAY=${DISPLAY}
  devices:
    - /dev/bus/usb:/dev/bus/usb


#######################
###   Image Build   ###
#######################
services:
  nav2-build:
    build: 
      context: .  
      dockerfile: Dockerfile
    <<: *shared-settings
    container_name: nav2-build
    command: >
      /bin/bash -c "
      cd /root/nav2-ws
      "

#############################
###   Container Startup   ###
#############################
  exploration-mode:
    <<: *shared-settings
    container_name: exploration-mode