services:
  svelte:
    build: 
      context: .  
      dockerfile: Dockerfile
    image: pomelo925/ttennis-humble:svelte
    container_name: svelte-app
    privileged: true
    ports:
      - "3000:3000"
    # volumes:
      # - .:/app
      # - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true