services:
  EdgeNN:
    build: 
      context: .  
      dockerfile: Dockerfile
    image: pomelo925/ttennis-humble:edgenn
    container_name: edgenn-build
    tty: true
    network_mode: host
    privileged: true

    # command: >
    #   /bin/bash -c "
    #   cd /home/extraction-ws 
    #   && catkin_make
    #   && chmod +x /home/extraction-ws/devel/lib/diff-rs-pcl2/*
    #   && chmod +x /home/extraction-ws/devel/lib/univ-rs-pcl2/*
    #   && cd /home/realsense-ws 
    #   && catkin_make
    #   "