services:
  RTABMap:
    image: pomelo925/ttennis-humble:rtabmap
    container_name: rtabmap-run
    tty: true
    network_mode: host
    privileged: true

    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority

    environment:
      - DISPLAY=${DISPLAY}
    
    devices:
      - /dev/bus/usb  
    
    # command: >
      # /bin/bash -c "rtabmap"