// layout.jsx
import { JetBrains_Mono } from 'next/font/google';
import './globals.css';

// components
import HeaderClient from '@/components/HeaderClient';
import PageTransition from '@/components/PageTransition';

// 引入 JetBrains Mono 字體
const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  weights: ['100', '200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-jetbrainsMono',
});

export const metadata = {
  title: 'TTennis UI APP',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable}>
        <HeaderClient/>
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
