#############################
###   shared settings     ###
#############################
x-shared-settings: &shared-settings
  build: 
    context: .  
    dockerfile: Dockerfile
    target: final
  image: pomelo925/ttennis-humble:coordinator
  stdin_open: true
  tty: true
  network_mode: host
  privileged: true

  devices:
    - /dev:/dev
    

#############################
###   Container Startup   ###
#############################
services:
  navigation-deployment:
    <<: *shared-settings
    container_name: navigation-deployment

    command: "/bin/bash -c \"${COMMAND}\""
    environment:
    - DISPLAY=${DISPLAY}
    - COMMAND=${COMMAND}

    volumes:
    - /dev/shm:/dev/shm

    - ../app:/home/app
    - ../main-ws/build:/home/main-ws/build
    - ../main-ws/install:/home/main-ws/install
    - ../main-ws/src:/home/main-ws/src
