#############################
###   shared settings     ###
#############################
x-shared-settings: &shared-settings
  build: 
    context: .  
    dockerfile: Dockerfile
    target: final
  image: pomelo925/ttennis-humble:coordinator
  stdin_open: true
  tty: true
  network_mode: host
  privileged: true
  stop_grace_period: 1s


#############################
###   Container Startup   ###
#############################
services:
  coordinator-deployment:
    <<: *shared-settings
    container_name: coordinator-deployment
    
    volumes:
    - /dev/shm:/dev/shm

    - ../app:/home/app
    - ../main-ws/build:/home/main-ws/build
    - ../main-ws/install:/home/main-ws/install
    - ../main-ws/src:/home/main-ws/src

    environment:
    - DISPLAY=${DISPLAY}
    - COMMAND=${COMMAND}
    
    command: "/bin/bash -c \"${COMMAND}\""