name: Coordinator Image 

on:
  push:
    branches: [ main ]
    paths:
      - 3.Software/A.Coordinator/docker/Dockerfile
      - .github/workflows/coordinator.yml

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Repo Checkout 
      uses: actions/checkout@v3
    - 
      name: Docker meta
      id: meta
      # Ref: https://github.com/docker/metadata-action
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_POM_USERNAME }}/ttennis-humble
        tags: communication
    - 
      name: Docker Hub Log-in
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_POM_USERNAME }}
        password: ${{ secrets.DOCKERHUB_POM_ACCESS_TOKEN }}

    # Build Docker image
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: 3.Software/A.Coordinator/docker
        load: true # Load the image into Docker environment
        tags: ${{ steps.meta.outputs.tags }}
        push: false

    # Push Docker image to registry
    - name: Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: 3.Software/A.Coordinator/docker
        push: true
        tags: ${{ steps.meta.outputs.tags }}