name: docker

on:
  push:
    branches:
      - 'ros2'

jobs:
  docker:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        docker_tag: [humble, humble-latest, iron, iron-latest, jazzy-latest]
        include:
        - docker_tag: humble
          docker_path: 'humble'
          docker_platforms: |
            linux/amd64
        - docker_tag: humble-latest
          docker_path: 'humble/latest'
          docker_platforms: |
            linux/amd64
            linux/arm64
        - docker_tag: iron
          docker_path: 'iron'
          docker_platforms: |
            linux/amd64
        - docker_tag: iron-latest
          docker_path: 'iron/latest'
          docker_platforms: |
            linux/amd64
# Re-add "jazzy" after binaries are released
#        - docker_tag: jazzy
#          docker_path: 'jazzy'
#          docker_platforms: |
#            linux/amd64
        - docker_tag: jazzy-latest
          docker_path: 'jazzy/latest'
          docker_platforms: |
            linux/amd64
            linux/arm64
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: ${{ matrix.docker_platforms }}
          file: ./docker/${{ matrix.docker_path }}/Dockerfile
          tags: introlab3it/rtabmap_ros:${{ matrix.docker_tag }}
          cache-from: type=registry,ref=introlab3it/rtabmap_ros:${{ matrix.docker_tag }}
          cache-to: type=inline

